improve monitor to not show all tasks, show errors

diff --git a/bin/redact-monitor b/bin/redact-monitor
--- a/bin/redact-monitor
+++ b/bin/redact-monitor
@@ -5,6 +5,7 @@ require 'redis'
 require "redact"
 require 'sinatra/base'
 require 'ostruct'
+require 'json'
 
 class Server < Sinatra::Base
   def initialize redact
@@ -13,25 +14,33 @@ class Server < Sinatra::Base
   end
 
   get '/' do
-    enqueued = @redact.enqueued_tasks.map  { |t| OpenStruct.new t }
-    in_progress = @redact.in_progress_tasks.map { |t| OpenStruct.new t }
-    done = @redact.done_tasks.map { |t| OpenStruct.new t }
+    enqueued = @redact.enqueued_tasks(0, 10).map  { |t| OpenStruct.new t }
+    in_progress = @redact.in_progress_tasks(0, 10).map { |t| OpenStruct.new t }
+    done = @redact.done_tasks(0, 10).map { |t| OpenStruct.new t }
 
     (enqueued + in_progress + done).each do |x|
       x.ago = pretty_time_diff((Time.now - x.ts).abs)
       x.time_in_queue = x.time_waiting ? pretty_time_diff(x.time_waiting.to_i) : ""
       x.time_in_progress = x.time_processing ? pretty_time_diff(x.time_processing.to_i) : ""
-      x.params = x.params.map { |k, v| "<b>#{k}</b>: #{v}<br/>" }.join
+      x.params = (x.params || {}).map { |k, v| "<b>#{k}</b>: #{v}<br/>" }.join
+      x.send "error?=", (x.state == "error")
+      x.backtrace_html = JSON.parse(x.backtrace).map { |x| Rack::Utils.escape_html(x) }.join("<br/>") if x.backtrace
       x.state_happiness = case x.state
         when "done"; "success"
         when "error"; "danger"
         when "skipped"; "warning"
         when "in_progress"; x.tries > 0 ? "warning" : ""
       end
-
     end
 
-    erb :index, locals: { enqueued: enqueued, in_progress: in_progress, done: done }
+    erb :index, locals: {
+      enqueued: enqueued,
+      in_progress: in_progress,
+      done: done,
+      num_enqueued: @redact.num_enqueued_tasks,
+      num_in_progress: @redact.num_in_progress_tasks,
+      num_done: @redact.num_done_tasks,
+    }
   end
 
   def pretty_time_diff diff
